syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.sum.stock_trading_server.grpc";
option java_outer_classname = "StockTradingProto";

message StockRequest {
    string stock_symbol = 1;
}

message StockResponse {
    string stock_symbol = 1;
    double price = 2;
    string timestamp = 3;
}

message StockListResponse {
    repeated StockResponse stock_list = 1;
}

message AddStockRequest {
    string stock_symbol = 1;
    double price = 2;
}

message Empty {}

message StockOrderRequest {
    string order_id = 1;
    string stock_symbol = 2;
    int32 quantity = 3;
    double price = 4;
    string order_type = 5; // BUY OR SELL
}

message StockOrderSummary {
    int32 total_orders = 1;
    double total_amount = 2;
    int32 success_count = 3;
}

service StockTradingService {
    // UNARY METHODS
    // This method fetches current stock service
    rpc GetStock(StockRequest) returns (StockResponse);

    // This method fetches all stocks
    rpc GetAllStocks(Empty) returns (StockListResponse);

    // This method adds stocks
    rpc AddStock(AddStockRequest) returns (Empty);

    // This method deletes stocks
    rpc DeleteStock(StockRequest) returns (Empty);



    // SERVER STREAMING METHODS
    // Get stock prices
    rpc SubscribeStock(StockRequest) returns (stream StockResponse);



    // CLIENT STREAMING METHODS
    // Place Bulk Stock Orders
    rpc BulkStockOrder(stream StockOrderRequest) returns (StockOrderSummary);
}